#!/usr/bin/env python

import base64
import sys
from ast import literal_eval
from pathlib import Path

import jinja2
from dotenv import dotenv_values


def b64encode(str):
  return base64.b64encode(str.encode('utf-8')).decode('utf-8')

def main():
  root_path = Path('.')
  env_path = root_path / '.env'
  env = dotenv_values(env_path)
  tmpl_loader = jinja2.FileSystemLoader(searchpath=root_path)
  tmpl_env = jinja2.Environment(loader=tmpl_loader, autoescape=True)
  tmpl_env.filters['b64encode'] = b64encode
  tmpl = tmpl_env.get_template(sys.argv[1])
  tmpl_vars = {}
  for name, val in env.items():
    if name.endswith('[]'):
      name = name[:-2]
      val = literal_eval(val)
      assert type(val) is list
    name = name.lower()
    tmpl_vars[name] = val
  print(tmpl.render(**tmpl_vars))


if __name__ == '__main__':
  main()
