#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

CONTAINER_NAME=mobileconfigs-nginx
DEFAULT_PORT=8080

die() {
  echo "serve-configs: ${1:-something went wrong}"
  exit 1
}

usage() {
  cat <<EOF
usage: serve-configs [-h] [-p PORT]
options:
  -h        Print this help text and exit
  -p PORT   Use the specified port to run NGINX
EOF
}

main() {
  local port="$DEFAULT_PORT"
  while getopts ":hp:" opt; do
    case "$opt" in
      h)
        usage
        exit 0
        ;;
      p)
        port="$OPTARG"
        ;;
      :)
        die "option '-$OPTARG' requires an argument. See 'serve-configs -h'."
        ;;
      \?)
        die "unknown option '-$OPTARG'. See 'serve-configs -h'."
        ;;
    esac
  done
  docker run -d --rm --name "$CONTAINER_NAME" -p "$port:80" \
      -v "$(pwd)/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf" \
      -v "$(pwd)/public:/usr/share/nginx/html" nginx > /dev/null
  ip_addr="$(ip route get 1 | awk '{ print $(NF - 2); exit }')"
  echo "serve-configs: serving mobileconfigs at 'http://$ip_addr:$port/'."
  read -n 1 -s -r -p "serve-configs: press any key to exit..."
  docker stop "$CONTAINER_NAME" >& /dev/null || true
}

main "$@"
